- hosts: localhost
  connection: local
  gather_facts: True

  tasks:
  - vsphere_guest:
      $vcenter_hostname 
      $username 
      $password 
      validate_certs: no
      guest: jojjtestansible
      state: powered_off
      esxi:
        datacenter: Reading-Dev
        hostname: ukrdsesxi001.dbpoc.uk
